name = "memory-note"
kv_namespaces = [
    { binding = "MEMORY_NOTE", id = "5d96a29ca512466680e9e32601669ddd", preview_id = "89e03c9ccb1c48a68baf22d75f3d06fb" }
]
compatibility_date = "2023-01-01"
compatibility_flags = [ "nodejs_compat" ]
